### ISSUE TITLE
CXX from pythranrc

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#956] opened 2018-07-13 13:25 UTC
When compiling directly using pythran command line doesn't use CXX and CC from pythranrc file

**Comment by serge-sans-paille** [comment] 2018-07-16 06:49
Thanks @ashwinvis for the feedback. Looks like you're not using PythranBuildExt in  your setup.py, so the CXX override behavior is not activated. Funny enough, if I recall correctly, you were the one to advocate for that feature :-/

Am I missing something?

**Comment by serge-sans-paille** [comment] 2018-07-16 06:51
Adding ``cmdclass={"build_ext": PythranBuildExt},`` to your setup.py instead fixes the issue.

**Comment by ashwinvis** [comment] 2018-07-16 06:56
I am certainly missing something... Need some more time to track it down. My reply above was when I used PythranBuildExt.

I guess the catch i Pythran extensions arr built after C++ Cython extensions in fluidfft.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by serge-sans-paille** [comment] 2018-07-16 06:59
And anyway, we should not *ignore* CXX if ``PythranBuildExt`` is not used, I'll check that too.

**Comment by ashwinvis** [comment] 2018-07-16 07:01
No you are right.... It was my mistake. I was subclassing PythranBuildExt like:

```python
        from pythran.dist import PythranBuildExt

        class fluidfft_build_ext(build_ext, PythranBuildExt):
               pass
```

Certainly didn't work as intended. Worked when I tried `PythranBuildExt` explicitly.

**Comment by serge-sans-paille** [comment] 2018-07-16 09:54
And CXX is not ignored, I just forgot to set CC too, merging in that case

**Comment by serge-sans-paille** [comment] 2018-07-17 20:40
Fixed by #958

**Closed by serge-sans-paille** 2018-07-17 20:40 UTC
