### ISSUE TITLE
AttributeError: module 'gast' has no attribute 'Index'

### ISSUE THREAD

**Issue by martibosch** [serge-sans-paille/pythran#1628] opened 2020-09-01 12:38 UTC
Hello,

I am not sure whether this is more an issue of `gast` or `transonic`, but from the traceback I have the impression that it makes most sense to submit it here: installing the `pylandstats` package (which uses `pythran` through `transonic` to speed-up come Python functions) via pip raises an `AttributeError` as in:

```python
AttributeError: module 'gast' has no attribute 'Index'
```

You can see the full traceback and environment in [a dedicated build log](https://travis-ci.org/github/martibosch/pylandstats/builds/723062282). In short: 

* `gast-0.4.0`
* `pythran-0.9.6`
* `transonic-0.4.3`

Note that the linked build uses `pip` (instead of `conda`) to install the package. If instead install `pylandstats` as in `conda install -c conda-forge pylandstats`, the package is successfully installed despite that the exact same versions of `gast`, `pythran` and `transonic` are used.

Please let me know if you need any further information or if I should submit this issue elsewhere. Thank you in advance. Best,
Martí

**Comment by serge-sans-paille** [comment] 2020-09-01 12:49
This is a transonic issue: gast has upgraded to 0.4.0 and transonic hasn't catch up yet. You can bind gast to 0.3.3, or trnasonic should do so :-) cc @paugier

**Comment by martibosch** [comment] 2020-09-01 13:12
thank you for your answer. I tried binding gast to 0.3.3 as in:

```
conda create -n pylandstats python=3.7 gast=0.3.3 pythran transonic
# the actual versions installed by conda are `pythran-0.9.6` and `transonic-0.4.3`
```

followed by:

```
pip install pylandstats
```

and got the following error:

```bash
(pylandstats) martibosch@martibosch-ceat-desktop:~$ pip install pylandstats
Collecting pylandstats
  Downloading pylandstats-2.1.2.tar.gz (45 kB)
     |████████████████████████████████| 45 kB 433 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/martibosch/anaconda3/envs/pylandstats/bin/python3.7 /home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5ir2b52w
       cwd: /tmp/pip-install-_01igv_6/pylandstats
  Complete output (107 lines):
  INFO: /tmp/pip-install-_01igv_6/pylandstats/pylandstats/__pythran__/landscape.py written
  INFO: /tmp/pip-install-_01igv_6/pylandstats/pylandstats/__pythran__/landscape.pythran written
  INFO: File /tmp/pip-install-_01igv_6/pylandstats/pylandstats/__pythran__/landscape.py updated
  WARNING: 1 files created or updated needs to be pythranized
  /tmp/tmpkzxgipm_/source.c:1:10: fatal error: cblas.h: No such file or directory
   #include <cblas.h>
            ^~~~~~~~~
  compilation terminated.
  running egg_info
  writing pylandstats.egg-info/PKG-INFO
  writing dependency_links to pylandstats.egg-info/dependency_links.txt
  writing requirements to pylandstats.egg-info/requires.txt
  writing top-level names to pylandstats.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 79, in <module>
      ext_modules=extensions,
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 293, in run
      self.find_sources()
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 300, in find_sources
      mm.run()
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 531, in run
      self.add_defaults()
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 567, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 228, in add_defaults
      self._add_defaults_ext()
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 312, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 426, in get_source_files
      filenames.extend(ext.sources)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/dist.py", line 157, in sources
      module_name, cpponly=True)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/toolchain.py", line 475, in compile_pythranfile
      **kwargs)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/toolchain.py", line 395, in compile_pythrancode
      module_dir)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/toolchain.py", line 140, in generate_cxx
      entry_points=entry_points)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/toolchain.py", line 105, in front_middle_end
      refine(pm, ir, optimizations)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/middlend.py", line 43, in refine
      pm.gather(ExtendedSyntaxCheck, node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 217, in gather
      return a.run(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 143, in run
      return super(ModuleAnalysis, self).run(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 122, in run
      super(Analysis, self).run(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 95, in run
      self.prepare(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 90, in prepare
      result = d.run(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 143, in run
      return super(ModuleAnalysis, self).run(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 122, in run
      super(Analysis, self).run(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 96, in run
      return self.visit(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
      return super(ContextManager, self).visit(node)
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/ast.py", line 271, in visit
      return visitor(node)
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/ast.py", line 279, in generic_visit
      self.visit(item)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
      return super(ContextManager, self).visit(node)
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/ast.py", line 271, in visit
      return visitor(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/analyses/aliases.py", line 550, in visit_FunctionDef
      self.generic_visit(node)
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/ast.py", line 279, in generic_visit
      self.visit(item)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
      return super(ContextManager, self).visit(node)
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/ast.py", line 271, in visit
      return visitor(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/analyses/aliases.py", line 616, in visit_Assign
      value_aliases = self.visit(node.value)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
      return super(ContextManager, self).visit(node)
    File "/home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/ast.py", line 271, in visit
      return visitor(node)
    File "/tmp/pip-build-env-mmlfqb5d/overlay/lib/python3.7/site-packages/pythran/analyses/aliases.py", line 425, in visit_Subscript
      if isinstance(node.slice, ast.Index):
  AttributeError: module 'gast' has no attribute 'Index'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/martibosch/anaconda3/envs/pylandstats/bin/python3.7 /home/martibosch/anaconda3/envs/pylandstats/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5ir2b52w Check the logs for full command output.
```
I leave this information here in case it can be of any help to pythran or transonic. In any case, feel free to close this issue.

Best,
Martí

**Comment by paugier** [comment] 2020-09-01 13:29
Yes, I confirm that there is an issue with transonic 0.4.3 related to the new gast (0.4.0).

I'm going to release 2 new versions, first one with gast pin to 0.3.3 and a then a version compatible with gast 0.4.0 (https://foss.heptapod.net/fluiddyn/transonic/-/merge_requests/77).

However, the 2 tracebacks (here and in Travis) seem to show that transonic is not involved so there could also be a problem not related to transonic.

@serge-sans-paille transonic does not call itself Pythran analyses.

It could be an issue with pip and the isolated builds so that you get gast 0.4.0 for your build (even if before you installed gast 0.3.3 !).

I had to add `gast~=0.3.3` in `setup_requires` in fluidsim. I think all packages using Pythran could be affected by this problem.

**Comment by paugier** [comment] 2020-09-02 04:41
Note that pylandstats has a [pyproject.toml file](https://github.com/martibosch/pylandstats/blob/master/pyproject.toml] so pip uses its isolated build mode. Thus, it is totally useless to install particular build dependencies before the build.

Note that I don't know how the recent pip versions (with isolated builds) play with conda.

I guess there is a bug in pip about getting the right packages for the build. In your pyproject.toml, there is

```
[build-system]
requires = ['setuptools>=40.8.0', 'wheel', 'transonic>=0.4.0', 'pythran', 'numpy']
```

so you should get the most recent pythran (pythran 0.9.6) and pip should be able to install gast 0.3.3 and not gast 0.4.0 because pythran 0.9.6 requires gast~=0.3.3. However, this is not what you get and thus the bad pythran crash + traceback. It may be because transonic 0.4.3 simply requires "gast" (i.e. the lastest gast, which is now 0.4.0), but anyway, pip should be able to handle this situation.

**Comment by paugier** [comment] 2020-09-02 05:06
A nice way to reproduce your issue, where we clearly see the problem:

```
pierre@gre ~ $ python -m venv /tmp/venv_pylandstats                             
pierre@gre ~ $ source-bash /tmp/venv_pylandstats/bin/activate                   
(venv_pylandstats) pierre@gre ~ $ pip install pip -U                            
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.2.2
(venv_pylandstats) pierre@gre ~ $ pip install setuptools wheel numpy            
Requirement already satisfied: setuptools in /tmp/venv_pylandstats/lib/python3.8/site-packages (41.2.0)
Collecting wheel
  Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Collecting numpy
  Using cached numpy-1.19.1-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Installing collected packages: wheel, numpy
Successfully installed numpy-1.19.1 wheel-0.35.1
(venv_pylandstats) pierre@gre ~ $ pip install transonic pythran                 
Collecting transonic
  Using cached transonic-0.4.3-py3-none-any.whl (82 kB)
Collecting pythran
  Using cached pythran-0.9.6-py3-none-any.whl (4.4 MB)
Collecting astunparse>=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting beniget
  Using cached beniget-0.3.0-py3-none-any.whl (9.3 kB)
Collecting gast
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: numpy in /tmp/venv_pylandstats/lib/python3.8/site-packages (from transonic) (1.19.1)
Processing ./.cache/pip/wheels/5f/b4/93/a30fa45720240e1106155083bac98146542dd614e1e6ce12da/autopep8-1.5.4-py2.py3-none-any.whl
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting networkx>=2
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting ply>=3.4
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv_pylandstats/lib/python3.8/site-packages (from astunparse>=1.6.3->transonic) (0.35.1)
Collecting toml
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting pycodestyle>=2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Installing collected packages: six, astunparse, gast, beniget, toml, pycodestyle, autopep8, transonic, decorator, networkx, ply, pythran
Successfully installed astunparse-1.6.3 autopep8-1.5.4 beniget-0.3.0 decorator-4.4.2 gast-0.4.0 networkx-2.5 ply-3.11 pycodestyle-2.6.0 pythran-0.9.6 six-1.15.0 toml-0.10.1 transonic-0.4.3
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

pythran 0.9.6 requires beniget~=0.2.1, but you'll have beniget 0.3.0 which is incompatible.
pythran 0.9.6 requires gast~=0.3.3, but you'll have gast 0.4.0 which is incompatible.
```

Funny fact, there is no such problem with `pip install pythran transonic`!

Then, from this broken environment, the bug can be reproduced with 
`pip install pylandstats --no-build-isolation --no-binary pylandstats --force-reinstall`

**Comment by paugier** [comment] 2020-09-02 05:10
One can also check what happens with the pip flag `--use-feature=20` (and it's not good!)

(from a nearly empty environment)
```
(venv_pylandstats) pierre@gre ~ $ pip install transonic pythran --use-feature=20
20-resolver                                                                     
Collecting transonic
  Using cached transonic-0.4.3-py3-none-any.whl (82 kB)
Requirement already satisfied: numpy in /tmp/venv_pylandstats/lib/python3.8/site-packages (from transonic) (1.19.1)
Collecting astunparse>=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv_pylandstats/lib/python3.8/site-packages (from astunparse>=1.6.3->transonic) (0.35.1)
Collecting beniget
  Using cached beniget-0.3.0-py3-none-any.whl (9.3 kB)
Collecting gast
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting six<2.0,>=1.6.1
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pythran
  Using cached pythran-0.9.6-py3-none-any.whl (4.4 MB)
Collecting pythran
  Using cached pythran-0.9.5.tar.gz (3.6 MB)
Requirement already satisfied: numpy in /tmp/venv_pylandstats/lib/python3.8/site-packages (from transonic) (1.19.1)
Collecting ply>=3.4
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Collecting networkx>=2
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Processing ./.cache/pip/wheels/5f/b4/93/a30fa45720240e1106155083bac98146542dd614e1e6ce12da/autopep8-1.5.4-py2.py3-none-any.whl
Collecting pycodestyle>=2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting toml
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Building wheels for collected packages: pythran
  Building wheel for pythran (setup.py) ... done
  Created wheel for pythran: filename=pythran-0.9.5-py3-none-any.whl size=4066522 sha256=3cdbb6801fa2b6ff094f3d7e9829bdd7475d912d4921a334d1e8790fe7ccda27
  Stored in directory: /home/pierre/.cache/pip/wheels/e4/66/c1/1a5e2c8a2bb67eedaa1e9a2e004176d7116c6fdf2ec5a3e51b
Successfully built pythran
Installing collected packages: toml, six, pycodestyle, gast, decorator, ply, networkx, beniget, autopep8, astunparse, transonic, pythran
Successfully installed astunparse-1.6.3 autopep8-1.5.4 beniget-0.3.0 decorator-4.4.2 gast-0.4.0 networkx-2.5 ply-3.11 pycodestyle-2.6.0 pythran-0.9.5 six-1.15.0 toml-0.10.1 transonic-0.4.3
```

Pip choose pythran 0.9.5 which is indeed officially compatible with "gast" (the lastest gast) but which is actually not compatible with gast 0.4.0.

**Comment by paugier** [comment] 2020-09-02 07:53
The build associated with my PR is green. So it seems that it is a (hacky but) good solution for you @martibosch. 

In the meantime, I uploaded transonic 0.4.3.post1 (for which gast is pinned to 0.3.3) and transonic 0.4.4 compatible with gast 0.4.0.

Note that for you @martibosch it does not fix the problem because the situation is the same: most recent transonic version supporting "gast" and most recent pythran pinning gast to 0.3.3.

**Comment by paugier** [comment] 2020-09-02 08:47
I created an issue about the fact that the new resolver does not give a working solution https://github.com/pypa/pip/issues/8836

**Comment by martibosch** [comment] 2020-09-02 12:28
Thank you very much @paugier for going through this issue so thoroughly. I had also thought that it could be a conda/pip builds issue but decided to submit it here since it might be relevant to other packages using pythran/transonic.

PD: I have merged your PR and released a new patch of pylandstats (with some other fixes that are not in the scope of this discussion), thank you again @paugier

Best,
Martí

**Comment by serge-sans-paille** [comment] 2020-09-03 05:55
Thans a lot @paugier for the detailed walk through. I'll be closing the issue now :-)

**Closed by serge-sans-paille** 2020-09-03 05:55 UTC

**Comment by martibosch** [comment] 2020-09-03 07:28
Hello again,

I am sorry to still comment on this (I do not even expect @serge-sans-paille to re-open the issue, and we can move the discussion elsewhere), but [the conda-forge builds in the pylandstats-feedstock repository have failed for linux and osx](https://github.com/conda-forge/pylandstats-feedstock/pull/18) because of the same `AttributeError` (e.g., see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=204196&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=1362)).

You can see all the details in the Azure logs, but in short, the `AttributeError` was raised with gast-0.4.0, pythran-0.9.6 and transonic-0.4.4 (these are the versions installed in the conda environment before trying to build pylandstats-2.1.3 from the tar at PyPI - which includes [the merged PR](https://github.com/martibosch/pylandstats/pull/6) by @paugier changing the pythran/transonic order in `pyproject.toml`).

Any thoughts?

**Comment by paugier** [comment] 2020-09-03 07:44
I guess for conda the simpler would be to pin gast 0.3.3 in meta.yaml (in host and run).

**Comment by martibosch** [comment] 2020-09-03 10:09
Done. The pylandstats-2.1.3 recipe for conda-forge [pins gast to 0.3.3](https://github.com/conda-forge/pylandstats-feedstock/commit/d90f7a96b4e42f23ca17ce4846ddde6a237d95a2). All tests have passed. Thank you again.

Best,
Martí
