### ISSUE TITLE
conda recipe in Windows for a package using pythran 

### ISSUE THREAD

**Issue by martibosch** [serge-sans-paille/pythran#1325] opened 2019-07-19 08:45 UTC
I have created a [conda recipe](https://github.com/conda-forge/pylandstats-feedstock) to add the package [PyLandStats](https://github.com/martibosch/pylandstats) (which uses Pythran) to conda-forge. While creating the recipe has been kind of straight-forward, [it does not seem to work for Windows](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=52959), and I have not been able to get a clue of why the build fails from the error logs.

This is [the link to the latest pull request](https://github.com/conda-forge/pylandstats-feedstock/pull/1) with the respective platform-specific checks in Azure pipelines.

I leave here the traceback of the error on the build for Windows and Python 3.7:
```
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2324, in build_tree
    notest=notest,
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 1439, in build
    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)
  File "C:\Miniconda\lib\site-packages\conda_build\windows.py", line 294, in build
    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\Miniconda\lib\site-packages\conda_build\utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
##[error]Cmd.exe exited with code '1'.
```

**Comment by serge-sans-paille** [comment] 2019-09-07 15:15
The problem is related too the windows compiler, nt conda build, closing the issue as windows failure are already well documented :-/

**Closed by serge-sans-paille** 2019-09-07 15:15 UTC
