### ISSUE TITLE
test_clang_format fail 

### ISSUE THREAD

**Issue by louptheron** [serge-sans-paille/pythran#543] opened 2016-03-07 09:32 UTC
Hi,

I am having issue when launching test on archlinux (Linux version 4.3.3-2-ARCH) : 

I have done : 

    ____________________________________________________________ test_clang_format _____________________________________________________________
    
        def test_clang_format():
            """ Check coding style for cpp files. """ 
            pythran_dir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
            for root, _, _ in os.walk(os.path.join(pythran_dir, "pythonic")):
                for file_ in glob.glob(os.path.join(root, "*.hpp")):
                    cmd = "clang-format-3.6 {file} | diff -u {file} -".format(
                        file=os.path.join(root, file_))
                    process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
    >               assert not process.wait(), process.stdout.read()
    
    pythran/tests/test_format.py:15: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    obj = b'--- /home/distohm/archAurFiles/pythran/pythran/pythonic/core.hpp\t2016-03-07 09:21:44.087276203 +0100\n+++ -\t2016-0...ythonic/types/combined.hpp"\n-\n-#include "pythonic/types/int.hpp"\n-#include "pythonic/types/float.hpp"\n-\n-#endif\n'
    
        def _format_assertmsg(obj):
            """Format the custom assertion message given.
        
            For strings this simply replaces newlines with '\n~' so that
            util.format_explanation() will preserve them instead of escaping
            newlines.  For other objects py.io.saferepr() is used first.
        
            """ 
            # reprlib appears to have a bug which means that if a string
            # contains a newline it gets escaped, however if an object has a
            # .__repr__() which contains newlines it does not get escaped.
            # However in either case we want to preserve the newline.
            if py.builtin._istext(obj) or py.builtin._isbytes(obj):
                s = obj 
                is_repr = False
            else:
                s = py.io.saferepr(obj)
                is_repr = True
            if py.builtin._istext(s):
                t = py.builtin.text
            else:
                t = py.builtin.bytes
    >       s = s.replace(t("\n"), t("\n~")).replace(t("%"), t("%%"))
    E       TypeError: string argument without an encoding
    
    ../../lab/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:394: TypeError
    ----------------------------------------------------------- Captured stderr call -----------------------------------------------------------
    /bin/sh: clang-format-3.6 : commande introuvable
    
I installed clang 3.7.1-1 from arch repository but it did not solve the issue.

Thank you

**Comment by serge-sans-paille** [comment] 2016-03-07 09:36
Hi @louptheron 
The problem is we rely on clang-format-3.6, and if we upgrade to clang-format-3.7, it changes some part of the C++ files layout. Nothing to do with the inner pythran mechanism, you can safely ignore the error (or disable this test by commenting the function in pythran/tests/test_format.py)

@pbrunet do you think we should upgrade to clang-format-3.7 for the validation?

**Comment by louptheron** [comment] 2016-03-07 11:12
Thank you @serge-sans-paille

**Comment by serge-sans-paille** [comment] 2016-03-07 17:52
#545 now detects if clang-format-3.6 is available, and ignore the test otherwise

**Comment by serge-sans-paille** [comment] 2016-03-09 20:30
#545 has been merged and fixes this issue!

**Closed by serge-sans-paille** 2016-03-09 20:30 UTC
