### ISSUE TITLE
Differents results each run !

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#561] opened 2016-04-20 16:12 UTC
I have this code::

    $ cat comp.py
    # -*- coding: UTF-8 -*-
    import numpy
    
    #pythran export good_bad_packed_pythran(uint8[][], uint8[])
    def good_bad_packed_pythran(dbp, mask):
        """
        pythran vectorial covering
    
        >>> dbp = np.load('db.npy')
        >>> masks = np.load('mask_data_test.npy')
        >>> mask6 = masks[6]
        >>> from comp import good_bad_packed_pythran
    
        >>> pos, neg = good_bad_packed_pythran(dbp, mask6); print(pos[:12])
        [ 5 16 24 32 40 42 49 59 63 74 75 78]
    
        >>> pos, neg = good_bad_packed_pythran(dbp, mask6); print(pos[:12])
        [ 5 16 24 32 33 34 35 36 40 42 43 84]
    
        >>> pos, neg = good_bad_packed_pythran(dbp, mask6); print(pos[:12])
        [ 5 16 24 32 33 34 35 49 59 65 66 84]
    
        >>> pos, neg = good_bad_packed_pythran(dbp, mask6); print(pos[:12])
        [ 5 16 24 32 33 34 35 40 42 43 49 59]
        """
        check = (numpy.bitwise_and(mask, dbp[:, 1:]) == mask).all(axis=1)
        pos = (dbp[:, 0] == 1) & check
        neg = (dbp[:, 0] == 0) & check
        pos = numpy.nonzero(pos)[0]
        neg = numpy.nonzero(neg)[0]
        return (pos, neg)

As you can see on the docstring each run we get a different result, -> Black Magic !?

Here is the data used: http://zettafox.com/data.zip

The correct result we get with the non pythran version of the code::

    def good_bad_packed_vec(dbp, mask):
        """ vectorial numpy covering 

        In [74]: p, n = good_bad_packed_vec(dbp, mask6); print(p[:12])
        [  5  34  66 121 180 181 193 227 309 314 322 337]
        In [75]: p, n = good_bad_packed_vec(dbp, mask6); print(p[:12])
        [  5  34  66 121 180 181 193 227 309 314 322 337]
        """
        check = (np.bitwise_and(mask, dbp[:, 1:]) == mask).all(axis=1)
        pos = (dbp[:, 0] == 1) & check
        neg = (dbp[:, 0] == 0) & check
        pos = np.nonzero(pos)[0]
        neg = np.nonzero(neg)[0]
        return (pos, neg)

**Comment by serge-sans-paille** [comment] 2016-04-20 17:42
looks like we're reading random pieces of memory, thanks @LuisBL for reporting this!

**Comment by serge-sans-paille** [comment] 2016-04-22 20:54
Just so you know: I can reproduce your issue on master branch

**Comment by serge-sans-paille** [comment] 2016-04-22 21:23
I can even tell you that it's a broadcasting issue on pythran side. I let the remaining for an other day ;-)

**Comment by serge-sans-paille** [comment] 2016-04-23 09:19
In fact it's a consequence of a known limitation: we don't support broadcasting as in [3,3] * [2,2,2,2] = [6,6,6,6], and you rely on this. I'll try to tackle this one, but it's not that easy.

**Comment by LuisBL** [comment] 2016-04-24 10:13
Great,
Say me if I can help. I can provide the faster pythran code I've get on this usecase.

**Comment by serge-sans-paille** [comment] 2016-05-10 14:42
#563 solves the issue (in terms of correctness) but the performance or your code are still terrible, I still need to work on it!

**Comment by serge-sans-paille** [comment] 2016-05-23 19:38
@LuisBL I finally fixed the broadcasting implementation and it runs decently fast. **But** I found an issue with bitwise operators, described in #569 that impacts your code. Let's close this issue once #563 is merged and start working on #569 ;-)

**Comment by serge-sans-paille** [comment] 2016-05-31 16:42
@LuisBL : closing the issue thanks to #563

**Closed by serge-sans-paille** 2016-05-31 16:42 UTC
