### ISSUE TITLE
np.log2(int value) is wrong when pythranized

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1026] opened 2018-09-20 22:00 UTC
This is a nasty one:
```
import numpy as np

# pythran export test(int)
def test(N):
    return np.log2(N),np.log2(N*1.)
```
returns two different values! The first one is int(log2(N))...

**Comment by jeanlaroche** [comment] 2018-09-20 23:08
As expected, this is also true of many other math functions, like np.sqrt(). I'm guessing you're casting the output to the input type, so you get float32 for a float32 input etc, but this clearly does not work when the input is an int!

**Comment by serge-sans-paille** [comment] 2018-09-26 01:30
This is a real issue. I'll investigate that right now.

**Comment by serge-sans-paille** [comment] 2018-09-26 01:35
mmmmh I cannot reproduce, can you check on master version?

**Comment by jeanlaroche** [comment] 2018-09-26 08:34
I will when I get back... Traveling at this time...

**Comment by jeanlaroche** [comment] 2018-09-28 16:07
If I force include the directory myself, I get the following error:
```
jlaroche-mbp:PythranBugs$ cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch x86_64 -pipe -DENABLE_PYTHON_MODULE -D__PYTHRAN__=2 -DENABLE_PYTHON_MODULE -D__PYTHRAN__=2 -DPYTHRAN_BLAS_BLAS -DPYTHRAN_BLAS_BLAS -I/Users/jlaroche/temp/pythran/pythran -I/Users/jlaroche/temp/pythran/pythran -I/Library/Python/2.7/site-packages/numpy/core/include -I/usr/local/Cellar/openblas/0.2.20/include -I/Library/Python/2.7/site-packages/numpy/core/include -I/usr/local/Cellar/openblas/0.2.20/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/tmpyQr74N.cpp -o /var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/tmpBwLTCB/var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/tmpyQr74N.o -std=c++11 -fno-math-errno -w -std=c++11 -fno-math-errno -w -I/Users/jlaroche/temp/pythran/third_party
In file included from /var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/tmpyQr74N.cpp:11:
In file included from /Users/jlaroche/temp/pythran/pythran/pythonic/include/numpy/log2.hpp:8:
In file included from /Users/jlaroche/temp/pythran/third_party/xsimd/xsimd.hpp:15:
In file included from /Users/jlaroche/temp/pythran/third_party/xsimd/math/xsimd_math.hpp:21:
/Users/jlaroche/temp/pythran/third_party/xsimd/math/xsimd_scalar.hpp:250:11: error: no member named 'sincosf' in the global
      namespace; did you mean '__sincosf'?
        ::sincosf(val, &s, &c);
        ~~^~~~~~~
          __sincosf
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:661:29: note:
      '__sincosf' declared here
__header_always_inline void __sincosf(float __x, float *__sinp, float *__cosp) {
                            ^
In file included from /var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/tmpyQr74N.cpp:11:
In file included from /Users/jlaroche/temp/pythran/pythran/pythonic/include/numpy/log2.hpp:8:
In file included from /Users/jlaroche/temp/pythran/third_party/xsimd/xsimd.hpp:15:
In file included from /Users/jlaroche/temp/pythran/third_party/xsimd/math/xsimd_math.hpp:21:
/Users/jlaroche/temp/pythran/third_party/xsimd/math/xsimd_scalar.hpp:260:11: error: no member named 'sincos' in the global
      namespace; did you mean '__sincos'?
        ::sincos(val, &s, &c);
        ~~^~~~~~
          __sincos
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/math.h:666:29: note:
      '__sincos' declared here
__header_always_inline void __sincos(double __x, double *__sinp, double *__cosp) {
                            ^
2 errors generated.
```

**Comment by serge-sans-paille** [comment] 2018-09-28 16:54
(fixed on IRC, but for the record)

xsimd is now a vendored dependency of Pythran. You just need to ``python setup.py build`` or ``python setup.py develop`` to fix that issue.

**Comment by jeanlaroche** [comment] 2018-09-28 16:55
OK My bad. I failed to run setup.py build. Once that's done, I can confirm that:
- In Linux, compilation succeeds and there's no bug (log2(N) is correct whether N is an int or not)
- In MacOS: I now get the following compilation error:
```
In file included from /var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/tmpkfkYCr.cpp:11:
In file included from /Users/jlaroche/temp/pythran/pythran/pythonic/include/numpy/log2.hpp:8:
In file included from /Users/jlaroche/temp/pythran/pythran/xsimd/xsimd.hpp:15:
In file included from /Users/jlaroche/temp/pythran/pythran/xsimd/math/xsimd_math.hpp:21:
/Users/jlaroche/temp/pythran/pythran/xsimd/math/xsimd_scalar.hpp:250:11: error: no member named 'sincosf' in the global namespace; did you mean '__sincosf'?
        ::sincosf(val, &s, &c);
```

**Comment by serge-sans-paille** [comment] 2018-09-28 20:32
ok, #1029 should fix the simd issue.

**Comment by jeanlaroche** [comment] 2018-09-28 20:47
Indeed it does on mac os. Great!

**Comment by serge-sans-paille** [comment] 2018-09-29 19:13
thanks o/

**Closed** 2018-09-29 19:13 UTC
