### ISSUE TITLE
some performance differences

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#801] opened 2018-03-04 14:01 UTC
Hi,
I'm doing some tests to see if I should move my cython code over to pythran (mainly for maintenance reasons). I'm trying to understand some of the performance implications of vector or loop operations. I wrote one test case, which I don't quite understand the reasons for the difference seen in the three cases below:
```python
#pythran export make_decision(complex128[], complex128[])
#pythran export make_decision(complex64[], complex64[])
def make_decision(E, symbols):
    L = E.shape[0]
    M = symbols.shape[0]
    syms_out = np.zeros(L, dtype=E.dtype)
    #omp parallel for
    for i in range(L):
        im = np.argmin(abs(E[i]-symbols)**2)
        syms_out[i] = symbols[im]
    return syms_out

#pythran export make_decision2(complex128[], complex128[])
#pythran export make_decision2(complex64[], complex64[])
def make_decision2(E, symbols):
    L = E.shape[0]
    M = symbols.shape[0]
    syms_out = np.zeros(L, dtype=E.dtype)
    #omp parallel for private(d0, d)
    for i in range(L):
        d0 = 1000
        for j in range(M):
            d = abs(E[i]-symbols[j])**2
            if d < d0:
                syms_out[i] = symbols[j]
                d0 = d
    return syms_out

#pythran export make_decision3(complex128[], complex128[])
#pythran export make_decision3(complex64[], complex64[])
def make_decision3(E, symbols):
    L = E.shape[0]
    M = symbols.shape[0]
    syms_out = np.zeros(L, dtype=E.dtype)
    #omp parallel for private(d0, d)
    for i in range(L):
        d0 = 1000
        for j in range(M):
            d = (np.real(E[i]) - np.real(symbols[j]))**2 + (np.imag(E[i]) - np.imag(symbols[j]))**2
            if d < d0:
                syms_out[i] = symbols[j]
                d0 = d
    return syms_out
```

If I run this I get the following:
```
In [6]: timeit pythran_equalisation.make_decision(s, sc)
3.03 ms ± 104 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: timeit pythran_equalisation.make_decision2(s, sc)
1.32 ms ± 25.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [8]: timeit pythran_equalisation.make_decision3(s, sc)
1.32 ms ± 28.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [10]: timeit pythran_equalisation.make_decision3(s.astype(np.complex64), sc.astype(np.complex64))
1.87 ms ± 35.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [11]: timeit pythran_equalisation.make_decision2(s.astype(np.complex64), sc.astype(np.complex64))
1.35 ms ± 32.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
One thing I don't quite understand is why make_decision3 performs worse for single precision complex. But also I assumed from the documentation that we should essentially get the same performance from vector operation as from expanding the loop, why do I see a difference of almost a factor 3?
Compile arguments were:
`pythran -O3 -ffast-math -march=native -funroll-loops -mfpmath=sse -fopenmp  pythran_equalisation.py`

**Comment by cycomanic** [comment] 2018-03-04 15:12
Sorry missed copying one line s and sc look like this:
```python
s=np.random.randn(2**16)+np.random.randn(2**16)*1.j ; sc=random.choice(s, 32)
```

**Comment by serge-sans-paille** [comment] 2018-03-04 15:51
Thanks for the detailed feedback! Could you run the bench with OpenMP too?

**Comment by serge-sans-paille** [comment] 2018-03-04 15:52
You can also try adding that to your ``~/.pythranrc``:

```
[pythran]
complex_hook = True
```

**Comment by serge-sans-paille** [comment] 2018-03-04 17:03
Without OpenMP, I get

```
(pythran) serge@lakota:~/sources/pythran (master)% python -m pythran.run md.py -Ofast -march=native
(pythran) serge@lakota:~/sources/pythran (master)% python -m perf timeit -s 'import numpy as np, random; np.random.seed(0); s=np.random.randn(2**16)+np.random.randn(2**16)*1.j ; sc=np.random.choice(s, 32); from md import md, md2' 'md(s, sc)'
.....................
Mean +- std dev: 32.1 ms +- 0.3 ms
(pythran) serge@lakota:~/sources/pythran (master)% python -m perf timeit -s 'import numpy as np, random; np.random.seed(0); s=np.random.randn(2**16)+np.random.randn(2**16)*1.j ; sc=np.random.choice(s, 32); from md import md, md2' 'md2(s, sc)'
.....................
Mean +- std dev: 38.4 ms +- 1.3 ms
```

So the problem is likely related to nested paraelism (OpenMP triggers //ion of the np.abs computation too).

**Comment by cycomanic** [comment] 2018-03-04 17:44
OK slightly different formatting (easier to run this with pytest). The array length are slightly longer s is 2**20 items and sc 128 items. Below the numbers, method0 is my cython method method 4 is like this:
```python
#pythran export make_decision4(complex128[], complex128[])
#pythran export make_decision4(complex64[], complex64[])
def make_decision4(E, symbols):
    L = E.shape[0]
    M = symbols.shape[0]
    syms_out = np.zeros(L, dtype=E.dtype)
    #omp parallel for
    for i in range(L):
        syms_out[i] = det_symbol(E[i], symbols)
    return syms_out

def det_symbol(E, symbs):
    return symbs[np.argmin(abs(E - symbs)**2)]
```

all the other methods are like above. :

Without complex_hook=True
```
-------------------------------------------------------------------------------------- benchmark: 10 tests --------------------------------------------------------------------------------------
Name (time in ms)                                  Min                 Max                Mean            StdDev              Median               IQR            Outliers(*)  Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_quantize_methods[method2-complex64]       55.7579 (1.0)       61.6084 (1.03)      57.7644 (1.0)      1.4705 (1.45)      57.7127 (1.0)      1.4099 (1.23)             5;1      17           1
test_quantize_methods[method3-complex128]      56.4574 (1.01)      59.9905 (1.0)       58.4333 (1.01)     1.2608 (1.24)      58.7296 (1.02)     2.5114 (2.19)             7;0      17           1
test_quantize_methods[method0-complex128]      56.4865 (1.01)      78.9053 (1.32)      60.9568 (1.06)     5.7688 (5.68)      59.1433 (1.02)     3.7970 (3.31)             3;3      18           1
test_quantize_methods[method2-complex128]      56.8371 (1.02)      63.9201 (1.07)      58.8960 (1.02)     2.0406 (2.01)      58.4975 (1.01)     2.1145 (1.85)             3;2      18           1
test_quantize_methods[method0-complex64]       56.9466 (1.02)      60.9140 (1.02)      57.9295 (1.00)     1.0153 (1.0)       57.7672 (1.00)     1.1840 (1.03)             2;1      18           1
test_quantize_methods[method3-complex64]       91.7783 (1.65)     110.2057 (1.84)      95.4044 (1.65)     5.1653 (5.09)      93.5213 (1.62)     3.3887 (2.96)             1;1      11           1
test_quantize_methods[method1-complex64]      177.7011 (3.19)     185.1613 (3.09)     180.9870 (3.13)     3.0517 (3.01)     179.9298 (3.12)     5.4865 (4.79)             3;0       6           1
test_quantize_methods[method1-complex128]     177.9517 (3.19)     186.0178 (3.10)     181.1796 (3.14)     2.6585 (2.62)     180.9548 (3.14)     1.1458 (1.0)              2;2       6           1
test_quantize_methods[method4-complex64]      182.4016 (3.27)     201.6081 (3.36)     187.1742 (3.24)     7.2230 (7.11)     184.7138 (3.20)     3.3016 (2.88)             1;1       6           1
test_quantize_methods[method4-complex128]     184.2189 (3.30)     187.6729 (3.13)     185.9068 (3.22)     1.2461 (1.23)     185.6897 (3.22)     1.3206 (1.15)             2;0       5           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

With complex_hook =True 
```
--------------------------------------------------------------------------------------- benchmark: 10 tests ----------------------------------------------------------------------------------------
Name (time in ms)                                  Min                 Max                Mean             StdDev              Median                 IQR            Outliers(*)  Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_quantize_methods[method0-complex64]       56.0934 (1.0)       60.2446 (1.0)       57.6785 (1.0)       1.0761 (1.0)       57.7430 (1.00)       1.2153 (1.20)             5;1      18           1
test_quantize_methods[method0-complex128]      56.6497 (1.01)      78.8917 (1.31)      60.7544 (1.05)      5.4725 (5.09)      59.3011 (1.03)       3.2373 (3.19)             2;2      17           1
test_quantize_methods[method3-complex128]      56.9718 (1.02)      72.1897 (1.20)      59.6941 (1.03)      4.8628 (4.52)      57.6966 (1.0)        1.0141 (1.0)              3;3      18           1
test_quantize_methods[method3-complex64]       91.0602 (1.62)     128.0071 (2.12)      96.2986 (1.67)     11.2151 (10.42)     92.9007 (1.61)       2.6375 (2.60)             1;1      10           1
test_quantize_methods[method2-complex64]      213.2806 (3.80)     310.5958 (5.16)     238.4663 (4.13)     41.8621 (38.90)    214.9607 (3.73)      44.0458 (43.44)            1;0       5           1
test_quantize_methods[method1-complex64]      218.7423 (3.90)     230.1189 (3.82)     224.0302 (3.88)      4.6821 (4.35)     224.8722 (3.90)       7.6578 (7.55)             2;0       5           1
test_quantize_methods[method4-complex64]      221.9886 (3.96)     253.6465 (4.21)     232.8835 (4.04)     14.0282 (13.04)    224.5803 (3.89)      21.6291 (21.33)            1;0       5           1
test_quantize_methods[method2-complex128]     424.0490 (7.56)     644.8518 (10.70)    558.5201 (9.68)     93.6606 (87.04)    609.1058 (10.56)    143.8892 (141.89)           1;0       5           1
test_quantize_methods[method1-complex128]     458.6904 (8.18)     652.8080 (10.84)    509.7850 (8.84)     80.5142 (74.82)    476.6357 (8.26)      55.0268 (54.26)            1;1       5           1
test_quantize_methods[method4-complex128]     588.5936 (10.49)    830.9579 (13.79)    692.9543 (12.01)    88.3789 (82.13)    671.4154 (11.64)     90.0228 (88.77)            2;0       5           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Regarding OpenMP did you mean without (I assume my directives mean I have openMP enabled?)?  I assume simply omitting -fopenmp is enough? Results below:
Without complex_hook=True and no -fopenmp
```
--------------------------------------------------------------------------------------- benchmark: 10 tests ---------------------------------------------------------------------------------------
Name (time in ms)                                  Min                 Max                Mean             StdDev              Median                IQR            Outliers(*)  Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_quantize_methods[method0-complex64]       55.8561 (1.0)       59.5362 (1.0)       57.1674 (1.0)       1.0745 (1.31)      57.5971 (1.0)       1.7520 (1.35)             7;0      17           1
test_quantize_methods[method0-complex128]      56.5083 (1.01)      61.2796 (1.03)      58.5671 (1.02)      1.5637 (1.91)      58.6626 (1.02)      2.5927 (2.00)             7;0      17           1
test_quantize_methods[method2-complex128]     205.0444 (3.67)     207.8593 (3.49)     206.3637 (3.61)      1.1356 (1.39)     205.8997 (3.57)      1.7232 (1.33)             2;0       5           1
test_quantize_methods[method3-complex128]     205.6370 (3.68)     209.2594 (3.51)     207.4114 (3.63)      1.3000 (1.59)     207.5178 (3.60)      1.3423 (1.03)             2;0       5           1
test_quantize_methods[method2-complex64]      207.3704 (3.71)     209.3928 (3.52)     208.5282 (3.65)      0.8189 (1.0)      208.5516 (3.62)      1.2976 (1.0)              2;0       5           1
test_quantize_methods[method3-complex64]      340.5052 (6.10)     343.8162 (5.77)     342.0172 (5.98)      1.2773 (1.56)     341.9848 (5.94)      1.8725 (1.44)             2;0       5           1
test_quantize_methods[method1-complex64]      658.1712 (11.78)    669.8283 (11.25)    661.5210 (11.57)     4.7487 (5.80)     659.4021 (11.45)     4.1911 (3.23)             1;1       5           1
test_quantize_methods[method4-complex64]      659.9755 (11.82)    691.8012 (11.62)    671.3307 (11.74)    14.2332 (17.38)    663.1965 (11.51)    22.7946 (17.57)            1;0       5           1
test_quantize_methods[method1-complex128]     661.0424 (11.83)    666.6934 (11.20)    662.8689 (11.60)     2.3368 (2.85)     661.7414 (11.49)     2.9963 (2.31)             1;0       5           1
test_quantize_methods[method4-complex128]     681.2182 (12.20)    689.8238 (11.59)    684.4914 (11.97)     3.5764 (4.37)     682.8581 (11.86)     5.3783 (4.14)             1;0       5           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
With  complex_hook=True and without -fopenmp
```
------------------------------------------------------------------------------------------- benchmark: 10 tests -------------------------------------------------------------------------------------------
Name (time in ms)                                    Min                   Max                  Mean             StdDev                Median                IQR            Outliers(*)  Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_quantize_methods[method0-complex64]         57.1803 (1.0)         62.2183 (1.0)         59.2409 (1.0)       1.5714 (1.0)         58.7836 (1.0)       2.4190 (1.10)             6;0      17           1
test_quantize_methods[method0-complex128]        58.0268 (1.01)        65.0611 (1.05)        59.9713 (1.01)      1.8033 (1.15)        59.9038 (1.02)      2.1972 (1.0)              5;1      17           1
test_quantize_methods[method3-complex128]       201.2184 (3.52)       209.3968 (3.37)       206.3764 (3.48)      3.8075 (2.42)       208.5863 (3.55)      6.4658 (2.94)             1;0       5           1
test_quantize_methods[method3-complex64]        334.7706 (5.85)       349.4195 (5.62)       341.3594 (5.76)      6.6135 (4.21)       338.2686 (5.75)     11.5789 (5.27)             1;0       5           1
test_quantize_methods[method2-complex64]        800.6727 (14.00)      807.0530 (12.97)      803.2455 (13.56)     2.6851 (1.71)       802.6261 (13.65)     4.4314 (2.02)             1;0       5           1
test_quantize_methods[method1-complex64]        806.0968 (14.10)      816.5574 (13.12)      810.5920 (13.68)     3.7835 (2.41)       810.4326 (13.79)     3.4241 (1.56)             2;0       5           1
test_quantize_methods[method4-complex64]        809.6773 (14.16)      834.6349 (13.41)      820.6496 (13.85)    10.9724 (6.98)       821.0998 (13.97)    19.6303 (8.93)             1;0       5           1
test_quantize_methods[method2-complex128]     1,529.3848 (26.75)    1,597.3692 (25.67)    1,561.4063 (26.36)    25.5052 (16.23)    1,566.5790 (26.65)    32.5509 (14.81)            2;0       5           1
test_quantize_methods[method4-complex128]     1,579.6397 (27.63)    1,586.2435 (25.49)    1,583.6690 (26.73)     2.6403 (1.68)     1,584.0016 (26.95)     3.8454 (1.75)             1;0       5           1
test_quantize_methods[method1-complex128]     1,587.9521 (27.77)    1,606.4780 (25.82)    1,596.4256 (26.95)     6.9955 (4.45)     1,595.6687 (27.14)     9.6050 (4.37)             2;0       5           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

So it looks like complex_hook=True makes everything worse (except for my method3

**Comment by serge-sans-paille** [comment] 2018-07-26 05:53
Thread resurection, but for the greater good: #971 improves the situation *a lot* (without OpenMP) for the original algorithm that uses ``np.argmin``. @cycomanic can you confirm?

**Comment by serge-sans-paille** [comment] 2018-07-29 20:20
#971 has been merged, closing.

**Closed by serge-sans-paille** 2018-07-29 20:20 UTC

**Comment by cycomanic** [comment] 2018-08-01 18:54
Sorry for the late reply, I can confirm that #971 makes the original algorithm (`make_decision`) significantly faster. New test values:

```python
In [2]: s=np.random.randn(2**16)+np.random.randn(2**16)*1.j ; sc=random.choice(s, 32)

In [3]: timeit pythran_equalisation.make_decision(s, sc)
1.49 ms ± 47.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: timeit pythran_equalisation.make_decision2(s, sc)
2.09 ms ± 50.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [5]: timeit pythran_equalisation.make_decision3(s, sc)
2.11 ms ± 63.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Note that this is on a different computer so not absolutely comparable, however you can see that the method using `np.argmin` is now 1.3 times faster than the other methods compared to 3 times slower previously.

**Comment by serge-sans-paille** [comment] 2018-08-01 21:55
cool, thanks for the feedback and the great benchmark!
